<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>

        <base href="<?php echo $this->BASETAG;?>" target="_self"/>

        <?php echo $this->headMeta();?>
        <?php echo $this->headLink();?>
        <?php echo $this->headScript();?>
        
    </head>
        <body>
            <?php echo $this->layout()->content; ?>
        </body>
</html>
