<?php
    /** @var $this Zend_View_Interface */  
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>

        <base href="<?php echo $this->BASETAG;?>" target="_self"/>

        <?php echo $this->headMeta();?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headStyle();?>
        <?php echo $this->headLink();?>
        <?php echo $this->headScript();?>
        
    </head>
        <body>
            <div><?php echo $this->placeholder('login-widget');?></div>
            <?php echo $this->layout()->content; ?>
        </body>
</html>
